/* Automatically generated by './build/bin/build-entry.js' */

import Container from '../packages/container'
import Loading from '../packages/loading'
import Toast from '../packages/toast'
import Link from '../packages/link'
import SvgIcon from '../packages/svg-icon'
import RouterView from '../packages/router-view'
import filters from 'm2-vue/dist/filters'
import locale from 'm2-mobui/src/locale'
import EventBus from 'm2-mobui/src/utils/bus'

const components = [
  Container,
  Link,
  SvgIcon,
  RouterView
]

const install = (Vue, opts = {}) => {
  locale.use(opts.locale)
  locale.i18n(opts.i18n)

  components.forEach(component => {
    Vue.component(component.name, component)
  })

  filters.forEach(item => Vue.filter(item.name, item.rule))

  Vue.prototype.$bus = new EventBus()
  Vue.prototype.$m2 = {}
  Vue.prototype.$m2.loading = Loading
  Vue.prototype.$m2.loading.hide = Loading.hide
  Vue.prototype.$m2.toast = Toast
}

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  version: '1.0.1-beta.1',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  Container,
  Loading,
  Toast,
  Link,
  SvgIcon,
  RouterView
}
